### ISSUE TITLE
kullanım..

### ISSUE THREAD

**Issue by garsamba** [orhanmusellim/trendyol-php-api-class#1]
kullanım ile alakalı örnekleme vermeniz mümkünmü acaba..

**Comment by orhanmusellim** [comment]
Kütüphaneyi sayfaya dahil edip new diyerek başlatıyoruz. Daha sonra içerisindeki fonksiyonları kullanıyoruz.

$trendyol = new Trendyol();
$categories = $trendyol->->getCategories();
print_r($categories);

Bu şekilde Trendyol kategorilerini listeleyebilirsin.
